import styles from './BlogArticle.module.css';
import BlogHeader from './BlogHeader';

const BlogArticle = () => {
    return (
        <div>
            <BlogHeader />
            <div className={styles.blogarticle}>
                <img
                    className={styles.articleimgIcon}
                    alt=""
                    src="/images/BlogPost/articleImg.png"
                />
                <div className={styles.articlecontent}>
                    <div className={styles.maincontent}>
                        <b className={styles.articlemainheader}>
                            What is dry eye
                        </b>
                        <div className={styles.articlemaincontent}>
                            <p>
                                The dry eye disease or the dry eye syndrome is a broad term used to
                                refer to a collection of symptoms that affect the normal functioning
                                of eyes. The symptoms can include irritation, itching, redness,
                                grittiness (particle in the eye feeling etc). The symptoms can be
                                caused by various factors such as Meibomium Gland Dysfunction,
                                Acqueous deficiency, SJS disease, Schjoreign’s syndrome etc. As a dry
                                eye sufferer one of the most important steps is to understand the
                                mechanism in work behind the symptoms and investigate towards
                                underlying causes. The following chart can help addressing the
                                symptoms in a structured manner :
                            </p>
                            <p className={styles.embeddedImg}>
                                <img src="/images/BlogPost/embedded-article-imgs/dry-eye-chart.jpeg" />
                                <div>Chart to be created using photo below</div>
                            </p>
                            <ul>
                                <li>
                                    Take the dry eye quiz and find out if you have dry eye.
                                    <br />
                                    &lt;Add dry eye questionnaire&gt;
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div className={styles.subcontent}>
                        <div className={styles.articlesubheader}>
                            Diagnosed with MGD. Know what to do here.
                        </div>
                        <div className={styles.articlesubcontent}>
                            <p className="{styles.thereAreTimes}">
                                So you’ve taken the first big step to address your dry eyes.
                                Identifying that you have MGD is an important step in your dry eye
                                journey. MGD stands for Meibomian Gland Dysfunction. Meibomian Gland
                                is an important gland contained within our eyelids which have an
                                important function in maintaining our tearfilm. Our tearfilm has three
                                parts – aqueous, mucin and meibum. The meibum or the lipid part is
                                generated by the Meibomian gland.
                            </p>
                            <p>&lt;Insert Meibomian Gland image and tearfilm image&gt;</p>
                            <p>
                                This meibum plays an important part in maintaining our tearfilm and
                                preventing it from breaking or vaporizing. This tear film is
                                responsible to lubricate, hydrate and keep the eye surfaces in
                                functional condition. The absence of this film is what causes the Dry
                                eye symptoms. Therefore, once identified once should focus on
                                understanding the state of this film. There are many tests which can
                                help us understand the condition of this film. We’ll be considering
                                the most common ones. These are TBUT, NIBUT, LLT, Gland loss %. Let’s
                                see these one by one :
                            </p>
                            <ol>
                                <li>
                                    TBUT- Tear break up Time. It gives us a general idea as to how
                                    stable is patients tearfilm. The higher the value the healthier the
                                    eyes. NIBUT is a TBUT test carried out with a non-invasive
                                    instrument.
                                </li>
                                <li>
                                    LLT – Lipid layer thickness. This is an indication of how much
                                    meibum is present on the eye surface and eyelids. The higher the
                                    value the better it is.
                                </li>
                                <li>
                                    Gland loss% - Some MGD patients have glands which have disappeared
                                    or dropped out. The percentage of these dead glands gives a good
                                    indication to the severity of the problem. The less this percentage
                                    the better it is for the patients.
                                </li>
                            </ol>
                            <p>
                                There are more tests than the above available, if you want to know
                                more about them then please contact your doctor. We believe that the
                                above three tests establish a fair picture for a newly diagnosed dry
                                eye person. Please note that there are cases when the symptoms do not
                                correlate with the test readings. In such a case please investigate
                                with help of your healthcare professional.
                            </p>
                        </div>
                    </div>
                    <div className={styles.subcontent}>
                        <div className={styles.articlesubheader}>
                            Treatment
                        </div>
                        <div className={styles.articlesubcontent}>
                            <ol>
                                <li>Addressing the underlying cause</li>
                                <li>Controlling the symptoms</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div >
        </div>
    );
}
export default BlogArticle;